package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"log/slog"

	"github.com/petry-projects/markets-api/internal/audit"
	"github.com/petry-projects/markets-api/internal/auth"
	"github.com/petry-projects/markets-api/internal/domain"
	"github.com/petry-projects/markets-api/internal/gqlerr"
	"github.com/petry-projects/markets-api/internal/graph/generated"
	"github.com/petry-projects/markets-api/internal/graph/model"
)

// Empty is the resolver for the _empty field.
func (r *mutationResolver) Empty(ctx context.Context) (*bool, error) {
	return nil, gqlerr.NewError(gqlerr.CodeInternal, "not implemented")
}

// AuditLog is the resolver for the auditLog field.
// Manager-only, scoped to markets the manager is assigned to.
func (r *queryResolver) AuditLog(ctx context.Context, filter *model.AuditLogFilter, limit *int32, offset *int32) (*model.AuditLogConnection, error) {
	if err := auth.RequireRole(ctx, "manager"); err != nil {
		return nil, err
	}

	uid := auth.UserIDFromContext(ctx)
	if uid == "" {
		return nil, gqlerr.NewError(gqlerr.CodeUnauthenticated, "authentication required")
	}

	if r.AuditQuerier == nil {
		return nil, gqlerr.Internal("audit querier not configured")
	}

	if r.MarketRepo == nil {
		return nil, gqlerr.Internal("market repository not configured")
	}

	// Get all markets this manager is assigned to
	managedMarkets, err := r.MarketRepo.FindMarketsByManagerID(ctx, domain.UserID(uid))
	if err != nil {
		slog.Error("failed to find managed markets", "error", err, "userID", uid)
		return nil, gqlerr.Internal("failed to load managed markets")
	}

	marketIDs := make([]string, len(managedMarkets))
	for i, m := range managedMarkets {
		marketIDs[i] = m.ID.String()
	}

	// Build audit filter
	f := audit.Filter{}
	if filter != nil {
		f.ActorID = filter.ActorID
		f.ActionType = filter.ActionType
		f.TargetType = filter.TargetType
		f.TargetID = filter.TargetID
		f.MarketID = filter.MarketID
		f.StartDate = filter.StartDate
		f.EndDate = filter.EndDate
	}

	lim := 20
	if limit != nil {
		lim = int(*limit)
	}
	off := 0
	if offset != nil {
		off = int(*offset)
	}

	entries, totalCount, err := r.AuditQuerier.QueryForManagedMarkets(ctx, marketIDs, f, lim, off)
	if err != nil {
		slog.Error("failed to query audit log", "error", err, "userID", uid)
		return nil, gqlerr.Internal("failed to query audit log")
	}

	result := make([]*model.AuditLogEntry, len(entries))
	for i, e := range entries {
		result[i] = auditEntryToModel(&e)
	}

	return &model.AuditLogConnection{
		Entries:    result,
		TotalCount: int32(totalCount),
		HasMore:    off+lim < totalCount,
	}, nil
}

// MyActivityLog is the resolver for the myActivityLog field.
// Returns the authenticated user's own activity history from the audit log.
func (r *queryResolver) MyActivityLog(ctx context.Context, startDate *string, endDate *string, limit *int32, offset *int32) ([]*model.AuditLogEntry, error) {
	if err := auth.RequireRole(ctx, "customer", "vendor", "manager"); err != nil {
		return nil, err
	}

	uid := auth.UserIDFromContext(ctx)
	if uid == "" {
		return nil, gqlerr.NewError(gqlerr.CodeUnauthenticated, "authentication required")
	}

	if r.AuditQuerier == nil {
		return nil, gqlerr.Internal("audit querier not configured")
	}

	lim := 20
	if limit != nil {
		lim = int(*limit)
	}
	off := 0
	if offset != nil {
		off = int(*offset)
	}

	entries, err := r.AuditQuerier.QueryByActor(ctx, uid, startDate, endDate, lim, off)
	if err != nil {
		slog.Error("failed to query activity log", "error", err, "userID", uid)
		return nil, gqlerr.Internal("failed to query activity log")
	}

	result := make([]*model.AuditLogEntry, len(entries))
	for i, e := range entries {
		result[i] = auditEntryToModel(&e)
	}

	if result == nil {
		result = []*model.AuditLogEntry{}
	}

	return result, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
