package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"

	"github.com/petry-projects/markets-api/internal/auth"
	"github.com/petry-projects/markets-api/internal/gqlerr"
	"github.com/petry-projects/markets-api/internal/graph/generated"
	"github.com/petry-projects/markets-api/internal/graph/model"
)

// Empty is the resolver for the _empty field.
func (r *mutationResolver) Empty(ctx context.Context) (*bool, error) {
	return nil, gqlerr.NewError(gqlerr.CodeInternal, "not implemented")
}

// AuditLog is the resolver for the auditLog field.
func (r *queryResolver) AuditLog(ctx context.Context, filter *model.AuditLogFilter, limit *int32, offset *int32) (*model.AuditLogConnection, error) {
	if err := auth.RequireRole(ctx, "manager"); err != nil {
		return nil, err
	}
	return nil, gqlerr.NewError(gqlerr.CodeInternal, "not implemented")
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
