package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"strings"

	"github.com/petry-projects/markets-api/internal/auth"
	"github.com/petry-projects/markets-api/internal/db"
	"github.com/petry-projects/markets-api/internal/events"
	"github.com/petry-projects/markets-api/internal/gqlerr"
	"github.com/petry-projects/markets-api/internal/graph/model"
	"github.com/petry-projects/markets-api/internal/user"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	// Login is handled by Firebase Auth on the client side.
	// This resolver exists for schema completeness but is not used in the current flow.
	return nil, gqlerr.NewError(gqlerr.CodeInternal, "not implemented")
}

// SignUp is the resolver for the signUp field.
func (r *mutationResolver) SignUp(ctx context.Context, input model.SignUpInput) (*model.AuthPayload, error) {
	// SignUp is handled by Firebase Auth on the client side.
	// This resolver exists for schema completeness but is not used in the current flow.
	return nil, gqlerr.NewError(gqlerr.CodeInternal, "not implemented")
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.CreateUserPayload, error) {
	// CreateUser requires authentication but not a specific role (new users have no role yet)
	firebaseUID := auth.UserIDFromContext(ctx)
	if firebaseUID == "" {
		return nil, gqlerr.NewError(gqlerr.CodeUnauthenticated, "authentication required")
	}

	// Validate role input
	roleLower, ok := validRoles[input.Role]
	if !ok {
		return nil, gqlerr.ValidationError(fmt.Sprintf("invalid role: %s", input.Role))
	}

	// Validate name input
	name := strings.TrimSpace(input.Name)
	if name == "" {
		return nil, gqlerr.ValidationError("name is required")
	}
	if len(name) > 200 {
		return nil, gqlerr.ValidationError("name must be 200 characters or fewer")
	}

	// Extract email from auth context
	email := auth.EmailFromContext(ctx)

	// Create domain user
	u := &user.User{
		FirebaseUID: firebaseUID,
		Role:        roleLower,
		Name:        name,
		Email:       email,
	}

	// Insert into database
	if err := r.UserRepo.Create(ctx, u); err != nil {
		if errors.Is(err, db.ErrDuplicateUser) {
			return nil, gqlerr.Conflict("user record already exists")
		}
		slog.Error("failed to create user", "error", err, "firebaseUID", firebaseUID)
		return nil, gqlerr.Internal("failed to create user")
	}

	// Set Firebase custom claim
	claims := map[string]interface{}{
		"role": roleLower,
	}
	if err := r.ClaimsSetter.SetCustomUserClaims(ctx, firebaseUID, claims); err != nil {
		slog.Error("failed to set custom claims", "error", err, "firebaseUID", firebaseUID)
		// User was created in DB but claims failed - still return success
		// The client can retry token refresh
	}

	// Publish domain event after successful DB write
	r.EventBus.Publish(ctx, events.UserCreated{
		UserID: u.ID.String(),
		Role:   roleLower,
	})

	return &model.CreateUserPayload{
		User: &model.User{
			ID:          u.ID.String(),
			FirebaseUID: u.FirebaseUID,
			Email:       u.Email,
			DisplayName: u.Name,
			Role:        input.Role,
			CreatedAt:   u.CreatedAt.Format("2006-01-02T15:04:05Z07:00"),
			UpdatedAt:   u.CreatedAt.Format("2006-01-02T15:04:05Z07:00"),
		},
	}, nil
}

// DeleteAccount is the resolver for the deleteAccount field.
// Soft-deletes the authenticated user's account and all associated data.
// Only available to customer and vendor roles.
func (r *mutationResolver) DeleteAccount(ctx context.Context) (bool, error) {
	if err := auth.RequireRole(ctx, "customer", "vendor"); err != nil {
		return false, err
	}

	uid := auth.UserIDFromContext(ctx)
	if uid == "" {
		return false, gqlerr.NewError(gqlerr.CodeUnauthenticated, "authentication required")
	}

	role := auth.RoleFromContext(ctx)

	// Use a transaction to soft-delete all related records atomically
	tx, err := r.Pool.Begin(ctx)
	if err != nil {
		slog.Error("failed to begin transaction for account deletion", "error", err, "userID", uid)
		return false, gqlerr.Internal("failed to delete account")
	}
	defer tx.Rollback(ctx) //nolint:errcheck

	// Set session variables so audit triggers can record the actor
	if err := auth.SetSessionVars(ctx, tx, uid, role); err != nil {
		slog.Error("failed to set session vars", "error", err, "userID", uid)
		return false, gqlerr.Internal("failed to delete account")
	}

	// Soft-delete the user record
	_, err = tx.Exec(ctx, "UPDATE users SET deleted_at = NOW() WHERE id = $1 AND deleted_at IS NULL", uid)
	if err != nil {
		slog.Error("failed to soft-delete user", "error", err, "userID", uid)
		return false, gqlerr.Internal("failed to delete account")
	}

	if role == "vendor" {
		// Soft-delete vendor profile
		_, err = tx.Exec(ctx,
			"UPDATE vendors SET deleted_at = NOW() WHERE user_id = $1 AND deleted_at IS NULL", uid)
		if err != nil {
			slog.Error("failed to soft-delete vendor profile", "error", err, "userID", uid)
			return false, gqlerr.Internal("failed to delete account")
		}

		// Soft-delete vendor products (via vendor_id from vendors table)
		_, err = tx.Exec(ctx,
			`UPDATE vendor_products SET deleted_at = NOW()
			 WHERE vendor_id IN (SELECT id FROM vendors WHERE user_id = $1)
			 AND deleted_at IS NULL`, uid)
		if err != nil {
			slog.Error("failed to soft-delete vendor products", "error", err, "userID", uid)
			return false, gqlerr.Internal("failed to delete account")
		}

		// Soft-delete vendor roster entries (vendor_roster uses user_id)
		_, err = tx.Exec(ctx,
			"UPDATE vendor_roster SET deleted_at = NOW() WHERE vendor_id = $1 AND deleted_at IS NULL", uid)
		if err != nil {
			slog.Error("failed to soft-delete vendor roster entries", "error", err, "userID", uid)
			return false, gqlerr.Internal("failed to delete account")
		}
	}

	if role == "customer" {
		// Soft-delete customer profile
		_, err = tx.Exec(ctx,
			"UPDATE customers SET deleted_at = NOW() WHERE user_id = $1 AND deleted_at IS NULL", uid)
		if err != nil {
			slog.Error("failed to soft-delete customer profile", "error", err, "userID", uid)
			return false, gqlerr.Internal("failed to delete account")
		}

		// Soft-delete follows
		_, err = tx.Exec(ctx,
			`UPDATE follows SET deleted_at = NOW()
			 WHERE customer_id IN (SELECT id FROM customers WHERE user_id = $1)
			 AND deleted_at IS NULL`, uid)
		if err != nil {
			slog.Error("failed to soft-delete follows", "error", err, "userID", uid)
			return false, gqlerr.Internal("failed to delete account")
		}
	}

	if err := tx.Commit(ctx); err != nil {
		slog.Error("failed to commit account deletion", "error", err, "userID", uid)
		return false, gqlerr.Internal("failed to delete account")
	}

	// Publish domain event after successful commit
	r.EventBus.Publish(ctx, events.AccountDeleted{
		UserID: uid,
		Role:   role,
	})

	return true, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	if err := auth.RequireRole(ctx, "customer", "vendor", "manager"); err != nil {
		return nil, err
	}
	return nil, gqlerr.NewError(gqlerr.CodeInternal, "not implemented")
}
