package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"strings"

	"github.com/petry-projects/markets-api/internal/auth"
	"github.com/petry-projects/markets-api/internal/db"
	"github.com/petry-projects/markets-api/internal/events"
	"github.com/petry-projects/markets-api/internal/gqlerr"
	"github.com/petry-projects/markets-api/internal/graph/model"
	"github.com/petry-projects/markets-api/internal/user"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	// Login is handled by Firebase Auth on the client side.
	// This resolver exists for schema completeness but is not used in the current flow.
	return nil, gqlerr.NewError(gqlerr.CodeInternal, "not implemented")
}

// SignUp is the resolver for the signUp field.
func (r *mutationResolver) SignUp(ctx context.Context, input model.SignUpInput) (*model.AuthPayload, error) {
	// SignUp is handled by Firebase Auth on the client side.
	// This resolver exists for schema completeness but is not used in the current flow.
	return nil, gqlerr.NewError(gqlerr.CodeInternal, "not implemented")
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.CreateUserPayload, error) {
	// CreateUser requires authentication but not a specific role (new users have no role yet)
	firebaseUID := auth.UserIDFromContext(ctx)
	if firebaseUID == "" {
		return nil, gqlerr.NewError(gqlerr.CodeUnauthenticated, "authentication required")
	}

	// Validate role input
	roleLower, ok := validRoles[input.Role]
	if !ok {
		return nil, gqlerr.ValidationError(fmt.Sprintf("invalid role: %s", input.Role))
	}

	// Validate name input
	name := strings.TrimSpace(input.Name)
	if name == "" {
		return nil, gqlerr.ValidationError("name is required")
	}
	if len(name) > 200 {
		return nil, gqlerr.ValidationError("name must be 200 characters or fewer")
	}

	// Extract email from auth context
	email := auth.EmailFromContext(ctx)

	// Create domain user
	u := &user.User{
		FirebaseUID: firebaseUID,
		Role:        roleLower,
		Name:        name,
		Email:       email,
	}

	// Insert into database
	if err := r.UserRepo.Create(ctx, u); err != nil {
		if errors.Is(err, db.ErrDuplicateUser) {
			return nil, gqlerr.Conflict("user record already exists")
		}
		slog.Error("failed to create user", "error", err, "firebaseUID", firebaseUID)
		return nil, gqlerr.Internal("failed to create user")
	}

	// Set Firebase custom claim
	claims := map[string]interface{}{
		"role": roleLower,
	}
	if err := r.ClaimsSetter.SetCustomUserClaims(ctx, firebaseUID, claims); err != nil {
		slog.Error("failed to set custom claims", "error", err, "firebaseUID", firebaseUID)
		// User was created in DB but claims failed - still return success
		// The client can retry token refresh
	}

	// Publish domain event after successful DB write
	r.EventBus.Publish(ctx, events.UserCreated{
		UserID: u.ID.String(),
		Role:   roleLower,
	})

	return &model.CreateUserPayload{
		User: &model.User{
			ID:          u.ID.String(),
			FirebaseUID: u.FirebaseUID,
			Email:       u.Email,
			DisplayName: u.Name,
			Role:        input.Role,
			CreatedAt:   u.CreatedAt.Format("2006-01-02T15:04:05Z07:00"),
			UpdatedAt:   u.CreatedAt.Format("2006-01-02T15:04:05Z07:00"),
		},
	}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	if err := auth.RequireRole(ctx, "customer", "vendor", "manager"); err != nil {
		return nil, err
	}
	return nil, gqlerr.NewError(gqlerr.CodeInternal, "not implemented")
}
