package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	"github.com/petry-projects/markets-api/internal/auth"
	"github.com/petry-projects/markets-api/internal/graph/model"
)

// CreateMarket is the resolver for the createMarket field.
func (r *mutationResolver) CreateMarket(ctx context.Context, input model.CreateMarketInput) (*model.Market, error) {
	if err := auth.RequireRole(ctx, "manager"); err != nil {
		return nil, err
	}
	panic(fmt.Errorf("not implemented: CreateMarket - createMarket"))
}

// UpdateMarket is the resolver for the updateMarket field.
func (r *mutationResolver) UpdateMarket(ctx context.Context, id string, input model.UpdateMarketInput) (*model.Market, error) {
	if err := auth.RequireRole(ctx, "manager"); err != nil {
		return nil, err
	}
	panic(fmt.Errorf("not implemented: UpdateMarket - updateMarket"))
}

// AddMarketSchedule is the resolver for the addMarketSchedule field.
func (r *mutationResolver) AddMarketSchedule(ctx context.Context, input model.AddScheduleInput) (*model.MarketSchedule, error) {
	if err := auth.RequireRole(ctx, "manager"); err != nil {
		return nil, err
	}
	panic(fmt.Errorf("not implemented: AddMarketSchedule - addMarketSchedule"))
}

// UpdateRosterStatus is the resolver for the updateRosterStatus field.
func (r *mutationResolver) UpdateRosterStatus(ctx context.Context, id string, status model.RosterStatus) (*model.VendorRosterEntry, error) {
	if err := auth.RequireRole(ctx, "manager"); err != nil {
		return nil, err
	}
	panic(fmt.Errorf("not implemented: UpdateRosterStatus - updateRosterStatus"))
}

// Market is the resolver for the market field.
func (r *queryResolver) Market(ctx context.Context, id string) (*model.Market, error) {
	if err := auth.RequireRole(ctx, "customer", "vendor", "manager"); err != nil {
		return nil, err
	}
	panic(fmt.Errorf("not implemented: Market - market"))
}

// Markets is the resolver for the markets field.
func (r *queryResolver) Markets(ctx context.Context, latitude *float64, longitude *float64, radiusMiles *float64, limit *int32, offset *int32) ([]*model.Market, error) {
	if err := auth.RequireRole(ctx, "customer", "vendor", "manager"); err != nil {
		return nil, err
	}
	panic(fmt.Errorf("not implemented: Markets - markets"))
}
