package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	"github.com/petry-projects/markets-api/internal/graph/model"
)

// UpdateNotificationPreferences is the resolver for the updateNotificationPreferences field.
func (r *mutationResolver) UpdateNotificationPreferences(ctx context.Context, input model.UpdateNotificationPreferencesInput) (*model.NotificationPreferences, error) {
	panic(fmt.Errorf("not implemented: UpdateNotificationPreferences - updateNotificationPreferences"))
}

// RegisterDeviceToken is the resolver for the registerDeviceToken field.
func (r *mutationResolver) RegisterDeviceToken(ctx context.Context, input model.RegisterDeviceTokenInput) (*model.DeviceToken, error) {
	panic(fmt.Errorf("not implemented: RegisterDeviceToken - registerDeviceToken"))
}

// RemoveDeviceToken is the resolver for the removeDeviceToken field.
func (r *mutationResolver) RemoveDeviceToken(ctx context.Context, tokenID string) (bool, error) {
	panic(fmt.Errorf("not implemented: RemoveDeviceToken - removeDeviceToken"))
}

// MyNotificationPreferences is the resolver for the myNotificationPreferences field.
func (r *queryResolver) MyNotificationPreferences(ctx context.Context) (*model.NotificationPreferences, error) {
	panic(fmt.Errorf("not implemented: MyNotificationPreferences - myNotificationPreferences"))
}
