package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"errors"
	"log/slog"
	"strings"
	"time"

	"github.com/petry-projects/markets-api/internal/auth"
	"github.com/petry-projects/markets-api/internal/domain"
	"github.com/petry-projects/markets-api/internal/events"
	"github.com/petry-projects/markets-api/internal/gqlerr"
	"github.com/petry-projects/markets-api/internal/graph/model"
	"github.com/petry-projects/markets-api/internal/vendor"
)

// CreateVendorProfile is the resolver for the createVendorProfile field.
func (r *mutationResolver) CreateVendorProfile(ctx context.Context, input model.CreateVendorProfileInput) (*model.Vendor, error) {
	if err := auth.RequireRole(ctx, "vendor"); err != nil {
		return nil, err
	}

	uid := auth.UserIDFromContext(ctx)
	if uid == "" {
		return nil, gqlerr.NewError(gqlerr.CodeUnauthenticated, "authentication required")
	}

	v, err := vendor.NewVendor(vendor.NewVendorParams{
		UserID:          domain.UserID(uid),
		BusinessName:    input.BusinessName,
		Description:     ptrToString(input.Description),
		ContactInfo:     ptrToString(input.ContactInfo),
		InstagramHandle: ptrToString(input.InstagramHandle),
		FacebookURL:     ptrToString(input.FacebookURL),
		WebsiteURL:      ptrToString(input.WebsiteURL),
		ImageURL:        ptrToString(input.ImageURL),
	})
	if err != nil {
		return nil, gqlerr.ValidationError(err.Error())
	}

	created, err := r.VendorRepo.CreateVendor(ctx, v)
	if err != nil {
		slog.Error("failed to create vendor profile", "error", err, "userID", uid)
		return nil, gqlerr.Internal("failed to create vendor profile")
	}

	r.EventBus.Publish(ctx, events.VendorProfileCreated{
		VendorID: created.ID.String(),
		UserID:   uid,
	})

	return vendorToModel(created), nil
}

// UpdateVendorProfile is the resolver for the updateVendorProfile field.
func (r *mutationResolver) UpdateVendorProfile(ctx context.Context, input model.UpdateVendorProfileInput) (*model.Vendor, error) {
	if err := auth.RequireRole(ctx, "vendor"); err != nil {
		return nil, err
	}

	uid := auth.UserIDFromContext(ctx)
	if uid == "" {
		return nil, gqlerr.NewError(gqlerr.CodeUnauthenticated, "authentication required")
	}

	existing, err := r.VendorRepo.FindVendorByUserID(ctx, domain.UserID(uid))
	if err != nil {
		slog.Error("failed to find vendor profile", "error", err, "userID", uid)
		return nil, gqlerr.Internal("vendor profile not found")
	}

	if err := existing.Update(vendor.UpdateVendorParams{
		BusinessName:    input.BusinessName,
		Description:     input.Description,
		ContactInfo:     input.ContactInfo,
		InstagramHandle: input.InstagramHandle,
		FacebookURL:     input.FacebookURL,
		WebsiteURL:      input.WebsiteURL,
		ImageURL:        input.ImageURL,
	}); err != nil {
		return nil, gqlerr.ValidationError(err.Error())
	}

	updated, err := r.VendorRepo.UpdateVendor(ctx, existing)
	if err != nil {
		slog.Error("failed to update vendor profile", "error", err, "userID", uid)
		return nil, gqlerr.Internal("failed to update vendor profile")
	}

	r.EventBus.Publish(ctx, events.VendorProfileUpdated{
		VendorID: updated.ID.String(),
	})

	return vendorToModel(updated), nil
}

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.CreateProductInput) (*model.Product, error) {
	if err := auth.RequireRole(ctx, "vendor"); err != nil {
		return nil, err
	}

	uid := auth.UserIDFromContext(ctx)
	if uid == "" {
		return nil, gqlerr.NewError(gqlerr.CodeUnauthenticated, "authentication required")
	}

	v, err := r.VendorRepo.FindVendorByUserID(ctx, domain.UserID(uid))
	if err != nil {
		slog.Error("failed to find vendor", "error", err, "userID", uid)
		return nil, gqlerr.Internal("vendor profile not found")
	}

	p, err := vendor.NewProduct(vendor.NewProductParams{
		VendorID:    v.ID,
		Name:        input.Name,
		Description: ptrToString(input.Description),
		Category:    ptrToString(input.Category),
		ImageURL:    ptrToString(input.ImageURL),
	})
	if err != nil {
		return nil, gqlerr.ValidationError(err.Error())
	}

	created, err := r.VendorRepo.CreateProduct(ctx, p)
	if err != nil {
		slog.Error("failed to create product", "error", err, "vendorID", v.ID)
		return nil, gqlerr.Internal("failed to create product")
	}

	r.EventBus.Publish(ctx, events.ProductCreated{
		ProductID: created.ID.String(),
		VendorID:  v.ID.String(),
	})

	return productToModel(created), nil
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, id string, input model.UpdateProductInput) (*model.Product, error) {
	if err := auth.RequireRole(ctx, "vendor"); err != nil {
		return nil, err
	}

	uid := auth.UserIDFromContext(ctx)
	if uid == "" {
		return nil, gqlerr.NewError(gqlerr.CodeUnauthenticated, "authentication required")
	}

	// Verify ownership: product must belong to vendor's profile
	existing, err := r.VendorRepo.FindProductByID(ctx, domain.ProductID(id))
	if err != nil {
		slog.Error("failed to find product", "error", err, "productID", id)
		return nil, gqlerr.Internal("product not found")
	}

	v, err := r.VendorRepo.FindVendorByUserID(ctx, domain.UserID(uid))
	if err != nil || v.ID != existing.VendorID {
		return nil, gqlerr.NewError(gqlerr.CodeForbidden, "not authorized to update this product")
	}

	if err := existing.Update(vendor.UpdateProductParams{
		Name:        input.Name,
		Description: input.Description,
		Category:    input.Category,
		ImageURL:    input.ImageURL,
		IsAvailable: input.IsAvailable,
	}); err != nil {
		return nil, gqlerr.ValidationError(err.Error())
	}

	updated, err := r.VendorRepo.UpdateProduct(ctx, existing)
	if err != nil {
		slog.Error("failed to update product", "error", err, "productID", id)
		return nil, gqlerr.Internal("failed to update product")
	}

	r.EventBus.Publish(ctx, events.ProductUpdated{
		ProductID: updated.ID.String(),
	})

	return productToModel(updated), nil
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationResolver) DeleteProduct(ctx context.Context, id string) (bool, error) {
	if err := auth.RequireRole(ctx, "vendor"); err != nil {
		return false, err
	}

	uid := auth.UserIDFromContext(ctx)
	if uid == "" {
		return false, gqlerr.NewError(gqlerr.CodeUnauthenticated, "authentication required")
	}

	// Verify ownership
	existing, err := r.VendorRepo.FindProductByID(ctx, domain.ProductID(id))
	if err != nil {
		slog.Error("failed to find product", "error", err, "productID", id)
		return false, gqlerr.Internal("product not found")
	}

	v, err := r.VendorRepo.FindVendorByUserID(ctx, domain.UserID(uid))
	if err != nil || v.ID != existing.VendorID {
		return false, gqlerr.NewError(gqlerr.CodeForbidden, "not authorized to delete this product")
	}

	if err := r.VendorRepo.DeleteProduct(ctx, domain.ProductID(id)); err != nil {
		slog.Error("failed to delete product", "error", err, "productID", id)
		return false, gqlerr.Internal("failed to delete product")
	}

	r.EventBus.Publish(ctx, events.ProductDeleted{
		ProductID: id,
	})

	return true, nil
}

// CheckIn is the resolver for the checkIn field.
func (r *mutationResolver) CheckIn(ctx context.Context, input model.CheckInInput) (*model.CheckIn, error) {
	if err := auth.RequireRole(ctx, "vendor", "manager"); err != nil {
		return nil, err
	}

	uid := auth.UserIDFromContext(ctx)
	if uid == "" {
		return nil, gqlerr.NewError(gqlerr.CodeUnauthenticated, "authentication required")
	}

	v, err := r.VendorRepo.FindVendorByUserID(ctx, domain.UserID(uid))
	if err != nil {
		slog.Error("failed to find vendor", "error", err, "userID", uid)
		return nil, gqlerr.Internal("vendor profile not found")
	}

	// Check for active check-ins to detect conflicts
	activeCheckIns, err := r.VendorRepo.FindActiveCheckInsByVendor(ctx, v.ID)
	if err != nil {
		slog.Error("failed to find active check-ins", "error", err, "vendorID", v.ID)
		return nil, gqlerr.Internal("failed to verify check-in status")
	}

	if err := vendor.CheckConflict(activeCheckIns, domain.MarketID(input.MarketID)); err != nil {
		return nil, gqlerr.NewError(gqlerr.CodeValidationError, err.Error())
	}

	ci := vendor.NewCheckIn(vendor.NewCheckInParams{
		VendorID: v.ID,
		MarketID: domain.MarketID(input.MarketID),
	})

	created, err := r.VendorRepo.CreateCheckIn(ctx, ci)
	if err != nil {
		slog.Error("failed to create check-in", "error", err, "vendorID", v.ID, "marketID", input.MarketID)
		return nil, gqlerr.Internal("failed to check in")
	}

	r.EventBus.Publish(ctx, events.VendorCheckedIn{
		VendorID:  v.ID.String(),
		MarketID:  input.MarketID,
		Timestamp: created.CheckedInAt,
	})

	return checkInToModel(created), nil
}

// CheckOut is the resolver for the checkOut field.
func (r *mutationResolver) CheckOut(ctx context.Context, checkInID string) (*model.CheckIn, error) {
	if err := auth.RequireRole(ctx, "vendor", "manager"); err != nil {
		return nil, err
	}

	uid := auth.UserIDFromContext(ctx)
	if uid == "" {
		return nil, gqlerr.NewError(gqlerr.CodeUnauthenticated, "authentication required")
	}

	ci, err := r.VendorRepo.FindCheckInByID(ctx, domain.CheckInID(checkInID))
	if err != nil {
		return nil, gqlerr.NewError(gqlerr.CodeValidationError, "check-in not found")
	}

	// Verify ownership
	v, err := r.VendorRepo.FindVendorByUserID(ctx, domain.UserID(uid))
	if err != nil || v.ID != ci.VendorID {
		return nil, gqlerr.NewError(gqlerr.CodeForbidden, "not authorized to check out this check-in")
	}

	if err := ci.CheckOut(); err != nil {
		return nil, gqlerr.NewError(gqlerr.CodeValidationError, err.Error())
	}

	updated, err := r.VendorRepo.UpdateCheckIn(ctx, ci)
	if err != nil {
		slog.Error("failed to check out", "error", err, "checkInID", checkInID)
		return nil, gqlerr.Internal("failed to check out")
	}

	r.EventBus.Publish(ctx, events.VendorCheckedOut{
		VendorID:  v.ID.String(),
		MarketID:  ci.MarketID.String(),
		CheckInID: checkInID,
		Timestamp: *updated.CheckedOutAt,
	})

	return checkInToModel(updated), nil
}

// ReportException is the resolver for the reportException field.
func (r *mutationResolver) ReportException(ctx context.Context, input model.ExceptionStatusInput) (*model.CheckIn, error) {
	if err := auth.RequireRole(ctx, "vendor", "manager"); err != nil {
		return nil, err
	}

	uid := auth.UserIDFromContext(ctx)
	if uid == "" {
		return nil, gqlerr.NewError(gqlerr.CodeUnauthenticated, "authentication required")
	}

	ci, err := r.VendorRepo.FindCheckInByID(ctx, domain.CheckInID(input.CheckInID))
	if err != nil {
		return nil, gqlerr.NewError(gqlerr.CodeValidationError, "check-in not found")
	}

	// Verify ownership
	v, err := r.VendorRepo.FindVendorByUserID(ctx, domain.UserID(uid))
	if err != nil || v.ID != ci.VendorID {
		return nil, gqlerr.NewError(gqlerr.CodeForbidden, "not authorized to report exception for this check-in")
	}

	if err := ci.ReportException(input.Reason); err != nil {
		return nil, gqlerr.NewError(gqlerr.CodeValidationError, err.Error())
	}

	updated, err := r.VendorRepo.UpdateCheckIn(ctx, ci)
	if err != nil {
		slog.Error("failed to report exception", "error", err, "checkInID", input.CheckInID)
		return nil, gqlerr.Internal("failed to report exception")
	}

	r.EventBus.Publish(ctx, events.VendorExceptionReported{
		VendorID:  v.ID.String(),
		MarketID:  ci.MarketID.String(),
		CheckInID: input.CheckInID,
		Reason:    input.Reason,
		Timestamp: *updated.CheckedOutAt,
	})

	return checkInToModel(updated), nil
}

// Vendor is the resolver for the vendor field.
func (r *queryResolver) Vendor(ctx context.Context, id string) (*model.Vendor, error) {
	if err := auth.RequireRole(ctx, "customer", "vendor", "manager"); err != nil {
		return nil, err
	}

	if r.VendorRepo == nil {
		return nil, gqlerr.Internal("vendor repository not configured")
	}

	v, err := r.VendorRepo.FindVendorByID(ctx, domain.VendorID(id))
	if err != nil {
		if errors.Is(err, vendor.ErrVendorNotFound) {
			return nil, nil // return nil for not found (nullable field)
		}
		slog.Error("failed to load vendor", "error", err, "vendorID", id)
		return nil, gqlerr.Internal("failed to load vendor")
	}

	return vendorToModel(v), nil
}

// MyVendorProfile is the resolver for the myVendorProfile field.
func (r *queryResolver) MyVendorProfile(ctx context.Context) (*model.Vendor, error) {
	if err := auth.RequireRole(ctx, "vendor"); err != nil {
		return nil, err
	}

	uid := auth.UserIDFromContext(ctx)
	if uid == "" {
		return nil, gqlerr.NewError(gqlerr.CodeUnauthenticated, "authentication required")
	}

	if r.VendorRepo == nil {
		return nil, nil
	}

	v, err := r.VendorRepo.FindVendorByUserID(ctx, domain.UserID(uid))
	if err != nil {
		return nil, nil // no profile yet
	}

	return vendorToModel(v), nil
}

// VendorProducts is the resolver for the vendorProducts field.
func (r *queryResolver) VendorProducts(ctx context.Context, vendorID string) ([]*model.Product, error) {
	if err := auth.RequireRole(ctx, "customer", "vendor", "manager"); err != nil {
		return nil, err
	}

	if r.VendorRepo == nil {
		return nil, gqlerr.Internal("vendor repository not configured")
	}

	products, err := r.VendorRepo.FindProductsByVendorID(ctx, domain.VendorID(vendorID))
	if err != nil {
		slog.Error("failed to load vendor products", "error", err, "vendorID", vendorID)
		return nil, gqlerr.Internal("failed to load products")
	}

	result := make([]*model.Product, len(products))
	for i, p := range products {
		result[i] = productToModel(p)
	}
	return result, nil
}

// SearchMarketsToJoin is the resolver for the searchMarketsToJoin field.
func (r *queryResolver) SearchMarketsToJoin(ctx context.Context, input model.SearchMarketsInput) ([]*model.MarketSearchResult, error) {
	if err := auth.RequireRole(ctx, "vendor"); err != nil {
		return nil, err
	}

	if r.VendorRepo == nil || r.MarketRepo == nil {
		return nil, gqlerr.Internal("repository not configured")
	}

	uid := auth.UserIDFromContext(ctx)
	if uid == "" {
		return nil, gqlerr.NewError(gqlerr.CodeUnauthenticated, "authentication required")
	}

	searchTerm := ""
	if input.SearchTerm != nil {
		searchTerm = *input.SearchTerm
	}

	rows, err := r.VendorRepo.SearchMarkets(ctx, searchTerm, input.Latitude, input.Longitude, input.RadiusKm, input.Limit, input.Offset)
	if err != nil {
		slog.Error("failed to search markets", "error", err)
		return nil, gqlerr.Internal("failed to search markets")
	}

	// Collect vendor's roster dates for status lookup (vendor_roster uses user_id)
	rosterDates, _ := r.VendorRepo.GetVendorMarketDates(ctx, domain.UserID(uid))

	// Group roster dates by market for status
	marketStatuses := make(map[domain.MarketID]model.VendorMarketJoinStatus)
	for _, rd := range rosterDates {
		existing, ok := marketStatuses[rd.MarketID]
		status := rosterStatusToJoinStatus(rd.Status)
		if !ok {
			marketStatuses[rd.MarketID] = status
		} else if existing != status {
			mixed := model.VendorMarketJoinStatusMixed
			marketStatuses[rd.MarketID] = mixed
		}
	}

	results := make([]*model.MarketSearchResult, 0, len(rows))
	for _, row := range rows {
		// Load market details
		m, err := r.MarketRepo.FindMarketByID(ctx, row.MarketID)
		if err != nil {
			continue // skip markets that can't be loaded
		}

		result := &model.MarketSearchResult{
			Market:      marketToModel(m),
			DistanceKm:  row.DistanceKm,
			VendorCount: int32(row.VendorCount),
		}

		if s, ok := marketStatuses[row.MarketID]; ok {
			result.VendorStatus = &s
		}

		results = append(results, result)
	}

	return results, nil
}

// VendorMarkets is the resolver for the vendorMarkets field.
func (r *queryResolver) VendorMarkets(ctx context.Context) ([]*model.VendorMarketAssociation, error) {
	if err := auth.RequireRole(ctx, "vendor"); err != nil {
		return nil, err
	}

	if r.VendorRepo == nil || r.MarketRepo == nil {
		return nil, gqlerr.Internal("repository not configured")
	}

	uid := auth.UserIDFromContext(ctx)
	if uid == "" {
		return nil, gqlerr.NewError(gqlerr.CodeUnauthenticated, "authentication required")
	}

	rosterDates, err := r.VendorRepo.GetVendorMarketDates(ctx, domain.UserID(uid))
	if err != nil {
		slog.Error("failed to get vendor market dates", "error", err)
		return nil, gqlerr.Internal("failed to load vendor markets")
	}

	// Group by market
	type marketGroup struct {
		dates          []*model.VendorMarketDate
		statuses       map[string]bool
		nextUpcoming   string
	}
	groups := make(map[domain.MarketID]*marketGroup)
	var orderedMarkets []domain.MarketID

	for _, rd := range rosterDates {
		g, ok := groups[rd.MarketID]
		if !ok {
			g = &marketGroup{statuses: make(map[string]bool)}
			groups[rd.MarketID] = g
			orderedMarkets = append(orderedMarkets, rd.MarketID)
		}
		g.dates = append(g.dates, &model.VendorMarketDate{
			ID:     rd.ID,
			Date:   rd.Date,
			Status: dbStatusToRosterStatus(rd.Status),
		})
		g.statuses[rd.Status] = true
		// Track next upcoming date (dates are sorted, filter to future dates)
		if g.nextUpcoming == "" && (rd.Status == "approved" || rd.Status == "committed") && rd.Date >= time.Now().Format("2006-01-02") {
			g.nextUpcoming = rd.Date
		}
	}

	results := make([]*model.VendorMarketAssociation, 0, len(groups))
	for _, marketID := range orderedMarkets {
		g := groups[marketID]
		m, err := r.MarketRepo.FindMarketByID(ctx, marketID)
		if err != nil {
			continue
		}

		// Determine overall status
		status := determineJoinStatus(g.statuses)

		assoc := &model.VendorMarketAssociation{
			Market: marketToModel(m),
			Status: status,
			Dates:  g.dates,
		}
		if g.nextUpcoming != "" {
			assoc.NextUpcomingDate = &g.nextUpcoming
		}
		results = append(results, assoc)
	}

	return results, nil
}

// rosterStatusToJoinStatus maps a roster status string to the join status enum.
func rosterStatusToJoinStatus(status string) model.VendorMarketJoinStatus {
	switch status {
	case "pending":
		return model.VendorMarketJoinStatusPending
	case "approved", "committed":
		return model.VendorMarketJoinStatusApproved
	case "rejected":
		return model.VendorMarketJoinStatusRejected
	default:
		return model.VendorMarketJoinStatusPending
	}
}

// determineJoinStatus calculates the overall status from a set of date statuses.
func determineJoinStatus(statuses map[string]bool) model.VendorMarketJoinStatus {
	if len(statuses) == 0 {
		return model.VendorMarketJoinStatusPending
	}
	if len(statuses) == 1 {
		for s := range statuses {
			return rosterStatusToJoinStatus(s)
		}
	}
	return model.VendorMarketJoinStatusMixed
}

// dbStatusToRosterStatus maps lowercase DB status to uppercase GraphQL VendorRosterStatus.
func dbStatusToRosterStatus(status string) model.VendorRosterStatus {
	return model.VendorRosterStatus(strings.ToUpper(status))
}
