// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

// Activity feed item representing an action in the system.
type ActivityFeedItem struct {
	ID         string  `json:"id"`
	ActorID    string  `json:"actorID"`
	ActionType string  `json:"actionType"`
	TargetType string  `json:"targetType"`
	TargetID   string  `json:"targetID"`
	MarketID   *string `json:"marketID,omitempty"`
	Message    string  `json:"message"`
	CreatedAt  string  `json:"createdAt"`
}

type AddScheduleInput struct {
	MarketID     string       `json:"marketID"`
	ScheduleType ScheduleType `json:"scheduleType"`
	DayOfWeek    *int32       `json:"dayOfWeek,omitempty"`
	Frequency    *string      `json:"frequency,omitempty"`
	SeasonStart  *string      `json:"seasonStart,omitempty"`
	SeasonEnd    *string      `json:"seasonEnd,omitempty"`
	EventName    *string      `json:"eventName,omitempty"`
	EventDate    *string      `json:"eventDate,omitempty"`
	StartTime    string       `json:"startTime"`
	EndTime      string       `json:"endTime"`
	Label        *string      `json:"label,omitempty"`
}

type AuditLogConnection struct {
	Entries    []*AuditLogEntry `json:"entries"`
	TotalCount int32            `json:"totalCount"`
	HasMore    bool             `json:"hasMore"`
}

// Audit log query types (read-only, no mutations).
// Audit writes are handled exclusively by PostgreSQL triggers.
type AuditLogEntry struct {
	ID         string  `json:"id"`
	ActorID    string  `json:"actorID"`
	ActorRole  string  `json:"actorRole"`
	ActionType string  `json:"actionType"`
	TargetType string  `json:"targetType"`
	TargetID   string  `json:"targetID"`
	MarketID   *string `json:"marketID,omitempty"`
	Timestamp  string  `json:"timestamp"`
	Payload    *string `json:"payload,omitempty"`
}

type AuditLogFilter struct {
	ActorID    *string `json:"actorID,omitempty"`
	ActionType *string `json:"actionType,omitempty"`
	TargetType *string `json:"targetType,omitempty"`
	TargetID   *string `json:"targetID,omitempty"`
	MarketID   *string `json:"marketID,omitempty"`
	StartDate  *string `json:"startDate,omitempty"`
	EndDate    *string `json:"endDate,omitempty"`
}

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type CheckIn struct {
	ID           string        `json:"id"`
	VendorID     string        `json:"vendorID"`
	MarketID     string        `json:"marketID"`
	Status       CheckInStatus `json:"status"`
	CheckedInAt  string        `json:"checkedInAt"`
	CheckedOutAt *string       `json:"checkedOutAt,omitempty"`
}

type CheckInInput struct {
	MarketID string `json:"marketID"`
	// Optional vendor ID for manager check-in on behalf (Story 5.3).
	VendorID *string `json:"vendorID,omitempty"`
}

type CreateMarketInput struct {
	Name         string            `json:"name"`
	Description  *string           `json:"description,omitempty"`
	Address      string            `json:"address"`
	Latitude     float64           `json:"latitude"`
	Longitude    float64           `json:"longitude"`
	ContactEmail string            `json:"contactEmail"`
	ContactPhone *string           `json:"contactPhone,omitempty"`
	SocialLinks  *SocialLinksInput `json:"socialLinks,omitempty"`
	ImageURL     *string           `json:"imageURL,omitempty"`
	// Recovery contact for the creating manager (email or phone). Required per FR41b.
	RecoveryContact string `json:"recoveryContact"`
}

type CreateProductInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Category    *string `json:"category,omitempty"`
	ImageURL    *string `json:"imageURL,omitempty"`
}

type CreateUserInput struct {
	Role Role   `json:"role"`
	Name string `json:"name"`
}

type CreateUserPayload struct {
	User *User `json:"user"`
}

type CreateVendorProfileInput struct {
	BusinessName    string  `json:"businessName"`
	Description     *string `json:"description,omitempty"`
	ContactInfo     *string `json:"contactInfo,omitempty"`
	InstagramHandle *string `json:"instagramHandle,omitempty"`
	FacebookURL     *string `json:"facebookURL,omitempty"`
	WebsiteURL      *string `json:"websiteURL,omitempty"`
	ImageURL        *string `json:"imageURL,omitempty"`
}

// Customer profile, follows, and discovery queries.
type CustomerProfile struct {
	ID              string    `json:"id"`
	UserID          string    `json:"userID"`
	DisplayName     string    `json:"displayName"`
	FollowedVendors []*Vendor `json:"followedVendors"`
	FollowedMarkets []*Market `json:"followedMarkets"`
	CreatedAt       string    `json:"createdAt"`
	UpdatedAt       string    `json:"updatedAt"`
}

type DeviceToken struct {
	ID        string   `json:"id"`
	UserID    string   `json:"userID"`
	Token     string   `json:"token"`
	Platform  Platform `json:"platform"`
	CreatedAt string   `json:"createdAt"`
}

type ExceptionStatusInput struct {
	CheckInID string `json:"checkInID"`
	Reason    string `json:"reason"`
}

type Follow struct {
	ID         string           `json:"id"`
	CustomerID string           `json:"customerID"`
	TargetType FollowTargetType `json:"targetType"`
	TargetID   string           `json:"targetID"`
	CreatedAt  string           `json:"createdAt"`
}

type FollowingFeedItem struct {
	ID        string  `json:"id"`
	Type      string  `json:"type"`
	Vendor    *Vendor `json:"vendor,omitempty"`
	Market    *Market `json:"market,omitempty"`
	Timestamp string  `json:"timestamp"`
	Message   string  `json:"message"`
}

type LoginInput struct {
	FirebaseToken string `json:"firebaseToken"`
}

// Market profile, schedule, and roster types.
// Managed by Market Managers.
type Market struct {
	ID                  string               `json:"id"`
	Name                string               `json:"name"`
	Description         *string              `json:"description,omitempty"`
	Address             string               `json:"address"`
	Latitude            float64              `json:"latitude"`
	Longitude           float64              `json:"longitude"`
	ContactEmail        string               `json:"contactEmail"`
	ContactPhone        *string              `json:"contactPhone,omitempty"`
	SocialLinks         *SocialLinks         `json:"socialLinks,omitempty"`
	ImageURL            *string              `json:"imageURL,omitempty"`
	RulesText           *string              `json:"rulesText,omitempty"`
	RulesUpdatedAt      *string              `json:"rulesUpdatedAt,omitempty"`
	Status              MarketStatus         `json:"status"`
	CancellationReason  *string              `json:"cancellationReason,omitempty"`
	CancellationMessage *string              `json:"cancellationMessage,omitempty"`
	CancelledAt         *string              `json:"cancelledAt,omitempty"`
	Managers            []*User              `json:"managers"`
	Schedule            []*MarketSchedule    `json:"schedule"`
	Vendors             []*VendorRosterEntry `json:"vendors"`
	CreatedAt           string               `json:"createdAt"`
	UpdatedAt           string               `json:"updatedAt"`
}

// Live attendance view for a market on a given day (Story 5.1).
type MarketAttendance struct {
	MarketID       string                   `json:"marketID"`
	Date           string                   `json:"date"`
	TotalRostered  int32                    `json:"totalRostered"`
	CheckedInCount int32                    `json:"checkedInCount"`
	PendingCount   int32                    `json:"pendingCount"`
	ExceptionCount int32                    `json:"exceptionCount"`
	Vendors        []*VendorAttendanceEntry `json:"vendors"`
}

// Planning view for a future market date.
type MarketDayPlan struct {
	Date             string               `json:"date"`
	VendorCount      int32                `json:"vendorCount"`
	CommittedVendors []*VendorRosterEntry `json:"committedVendors"`
	PendingRequests  []*VendorRosterEntry `json:"pendingRequests"`
}

type MarketSchedule struct {
	ID           string       `json:"id"`
	MarketID     string       `json:"marketID"`
	ScheduleType ScheduleType `json:"scheduleType"`
	// Day of week (0=Sunday, 6=Saturday). Only for RECURRING.
	DayOfWeek   *int32  `json:"dayOfWeek,omitempty"`
	Frequency   *string `json:"frequency,omitempty"`
	SeasonStart *string `json:"seasonStart,omitempty"`
	SeasonEnd   *string `json:"seasonEnd,omitempty"`
	// Event name. Only for ONE_TIME.
	EventName *string `json:"eventName,omitempty"`
	// Specific date. Only for ONE_TIME.
	EventDate *string `json:"eventDate,omitempty"`
	StartTime string  `json:"startTime"`
	EndTime   string  `json:"endTime"`
	Label     *string `json:"label,omitempty"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
}

// Search result for market browsing.
type MarketSearchResult struct {
	Market      *Market  `json:"market"`
	DistanceKm  *float64 `json:"distanceKm,omitempty"`
	VendorCount int32    `json:"vendorCount"`
	// The vendor's current status at this market, if any.
	VendorStatus *VendorMarketJoinStatus `json:"vendorStatus,omitempty"`
}

// A market-wide operational update (Story 5.4).
type MarketUpdate struct {
	ID        string `json:"id"`
	MarketID  string `json:"marketID"`
	SenderID  string `json:"senderID"`
	Message   string `json:"message"`
	CreatedAt string `json:"createdAt"`
}

// Root Mutation type - extended by each domain schema.
// No audit mutations exist; audit writes are DB trigger-only.
type Mutation struct {
}

// Notification preferences and device token management.
type NotificationPreferences struct {
	ID                   string `json:"id"`
	UserID               string `json:"userID"`
	PushEnabled          bool   `json:"pushEnabled"`
	VendorCheckInAlerts  bool   `json:"vendorCheckInAlerts"`
	VendorCheckoutAlerts bool   `json:"vendorCheckoutAlerts"`
	MarketUpdateAlerts   bool   `json:"marketUpdateAlerts"`
	ExceptionAlerts      bool   `json:"exceptionAlerts"`
	CreatedAt            string `json:"createdAt"`
	UpdatedAt            string `json:"updatedAt"`
}

type Product struct {
	ID          string  `json:"id"`
	VendorID    string  `json:"vendorID"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Category    *string `json:"category,omitempty"`
	ImageURL    *string `json:"imageURL,omitempty"`
	IsAvailable bool    `json:"isAvailable"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
}

// Root Query type - extended by each domain schema.
type Query struct {
}

type RegisterDeviceTokenInput struct {
	Token    string   `json:"token"`
	Platform Platform `json:"platform"`
}

type SearchMarketsInput struct {
	// Search term for market name, city, or category.
	SearchTerm *string  `json:"searchTerm,omitempty"`
	Latitude   *float64 `json:"latitude,omitempty"`
	Longitude  *float64 `json:"longitude,omitempty"`
	RadiusKm   *float64 `json:"radiusKm,omitempty"`
	Limit      *int32   `json:"limit,omitempty"`
	Offset     *int32   `json:"offset,omitempty"`
}

type SignUpInput struct {
	FirebaseToken string `json:"firebaseToken"`
	DisplayName   string `json:"displayName"`
	Role          Role   `json:"role"`
}

type SocialLinks struct {
	Instagram *string `json:"instagram,omitempty"`
	Facebook  *string `json:"facebook,omitempty"`
	Website   *string `json:"website,omitempty"`
	Twitter   *string `json:"twitter,omitempty"`
}

type SocialLinksInput struct {
	Instagram *string `json:"instagram,omitempty"`
	Facebook  *string `json:"facebook,omitempty"`
	Website   *string `json:"website,omitempty"`
	Twitter   *string `json:"twitter,omitempty"`
}

type UpdateMarketInput struct {
	Name         *string           `json:"name,omitempty"`
	Description  *string           `json:"description,omitempty"`
	Address      *string           `json:"address,omitempty"`
	Latitude     *float64          `json:"latitude,omitempty"`
	Longitude    *float64          `json:"longitude,omitempty"`
	ContactEmail *string           `json:"contactEmail,omitempty"`
	ContactPhone *string           `json:"contactPhone,omitempty"`
	SocialLinks  *SocialLinksInput `json:"socialLinks,omitempty"`
	ImageURL     *string           `json:"imageURL,omitempty"`
}

// Input for updating notification preferences.
type UpdateNotificationPreferencesInput struct {
	PushEnabled          *bool `json:"pushEnabled,omitempty"`
	VendorCheckInAlerts  *bool `json:"vendorCheckInAlerts,omitempty"`
	VendorCheckoutAlerts *bool `json:"vendorCheckoutAlerts,omitempty"`
	MarketUpdateAlerts   *bool `json:"marketUpdateAlerts,omitempty"`
	ExceptionAlerts      *bool `json:"exceptionAlerts,omitempty"`
}

type UpdateProductInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Category    *string `json:"category,omitempty"`
	ImageURL    *string `json:"imageURL,omitempty"`
	IsAvailable *bool   `json:"isAvailable,omitempty"`
}

type UpdateScheduleInput struct {
	DayOfWeek   *int32  `json:"dayOfWeek,omitempty"`
	Frequency   *string `json:"frequency,omitempty"`
	SeasonStart *string `json:"seasonStart,omitempty"`
	SeasonEnd   *string `json:"seasonEnd,omitempty"`
	EventName   *string `json:"eventName,omitempty"`
	EventDate   *string `json:"eventDate,omitempty"`
	StartTime   *string `json:"startTime,omitempty"`
	EndTime     *string `json:"endTime,omitempty"`
	Label       *string `json:"label,omitempty"`
}

type UpdateVendorProfileInput struct {
	BusinessName    *string `json:"businessName,omitempty"`
	Description     *string `json:"description,omitempty"`
	ContactInfo     *string `json:"contactInfo,omitempty"`
	InstagramHandle *string `json:"instagramHandle,omitempty"`
	FacebookURL     *string `json:"facebookURL,omitempty"`
	WebsiteURL      *string `json:"websiteURL,omitempty"`
	ImageURL        *string `json:"imageURL,omitempty"`
}

type User struct {
	ID          string `json:"id"`
	FirebaseUID string `json:"firebaseUID"`
	Email       string `json:"email"`
	DisplayName string `json:"displayName"`
	Role        Role   `json:"role"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

// Vendor profile, product catalog, and check-in types.
type Vendor struct {
	ID              string     `json:"id"`
	UserID          string     `json:"userID"`
	BusinessName    string     `json:"businessName"`
	Description     *string    `json:"description,omitempty"`
	ContactInfo     *string    `json:"contactInfo,omitempty"`
	InstagramHandle *string    `json:"instagramHandle,omitempty"`
	FacebookURL     *string    `json:"facebookURL,omitempty"`
	WebsiteURL      *string    `json:"websiteURL,omitempty"`
	ImageURL        *string    `json:"imageURL,omitempty"`
	Products        []*Product `json:"products"`
	CheckIns        []*CheckIn `json:"checkIns"`
	CreatedAt       string     `json:"createdAt"`
	UpdatedAt       string     `json:"updatedAt"`
}

// A vendor's attendance status for the attendance dashboard.
type VendorAttendanceEntry struct {
	VendorID     string             `json:"vendorID"`
	Vendor       *Vendor            `json:"vendor"`
	RosterStatus VendorRosterStatus `json:"rosterStatus"`
	CheckIn      *CheckIn           `json:"checkIn,omitempty"`
}

type VendorInvitation struct {
	ID          string           `json:"id"`
	MarketID    string           `json:"marketID"`
	VendorID    string           `json:"vendorID"`
	InvitedBy   string           `json:"invitedBy"`
	Status      InvitationStatus `json:"status"`
	TargetDates []string         `json:"targetDates,omitempty"`
	Message     *string          `json:"message,omitempty"`
	CreatedAt   string           `json:"createdAt"`
	UpdatedAt   string           `json:"updatedAt"`
}

// A market association for a vendor, showing status and committed dates.
type VendorMarketAssociation struct {
	Market           *Market                `json:"market"`
	Status           VendorMarketJoinStatus `json:"status"`
	Dates            []*VendorMarketDate    `json:"dates"`
	NextUpcomingDate *string                `json:"nextUpcomingDate,omitempty"`
}

// A single date commitment for a vendor at a market.
type VendorMarketDate struct {
	ID     string             `json:"id"`
	Date   string             `json:"date"`
	Status VendorRosterStatus `json:"status"`
}

type VendorNotification struct {
	ID       string `json:"id"`
	MarketID string `json:"marketID"`
	SenderID string `json:"senderID"`
	Message  string `json:"message"`
	SentAt   string `json:"sentAt"`
}

type VendorRosterEntry struct {
	ID                string             `json:"id"`
	MarketID          string             `json:"marketID"`
	VendorID          string             `json:"vendorID"`
	Vendor            *Vendor            `json:"vendor"`
	Status            VendorRosterStatus `json:"status"`
	Date              string             `json:"date"`
	InvitedBy         *string            `json:"invitedBy,omitempty"`
	RejectionReason   *string            `json:"rejectionReason,omitempty"`
	RulesAcknowledged bool               `json:"rulesAcknowledged"`
	CreatedAt         string             `json:"createdAt"`
	UpdatedAt         string             `json:"updatedAt"`
}

type CancellationReason string

const (
	CancellationReasonWeather       CancellationReason = "WEATHER"
	CancellationReasonEmergency     CancellationReason = "EMERGENCY"
	CancellationReasonLowAttendance CancellationReason = "LOW_ATTENDANCE"
	CancellationReasonOther         CancellationReason = "OTHER"
)

var AllCancellationReason = []CancellationReason{
	CancellationReasonWeather,
	CancellationReasonEmergency,
	CancellationReasonLowAttendance,
	CancellationReasonOther,
}

func (e CancellationReason) IsValid() bool {
	switch e {
	case CancellationReasonWeather, CancellationReasonEmergency, CancellationReasonLowAttendance, CancellationReasonOther:
		return true
	}
	return false
}

func (e CancellationReason) String() string {
	return string(e)
}

func (e *CancellationReason) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CancellationReason(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CancellationReason", str)
	}
	return nil
}

func (e CancellationReason) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CancellationReason) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CancellationReason) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CheckInStatus string

const (
	CheckInStatusCheckedIn  CheckInStatus = "CHECKED_IN"
	CheckInStatusCheckedOut CheckInStatus = "CHECKED_OUT"
	CheckInStatusException  CheckInStatus = "EXCEPTION"
)

var AllCheckInStatus = []CheckInStatus{
	CheckInStatusCheckedIn,
	CheckInStatusCheckedOut,
	CheckInStatusException,
}

func (e CheckInStatus) IsValid() bool {
	switch e {
	case CheckInStatusCheckedIn, CheckInStatusCheckedOut, CheckInStatusException:
		return true
	}
	return false
}

func (e CheckInStatus) String() string {
	return string(e)
}

func (e *CheckInStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CheckInStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CheckInStatus", str)
	}
	return nil
}

func (e CheckInStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CheckInStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CheckInStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FollowTargetType string

const (
	FollowTargetTypeVendor FollowTargetType = "VENDOR"
	FollowTargetTypeMarket FollowTargetType = "MARKET"
)

var AllFollowTargetType = []FollowTargetType{
	FollowTargetTypeVendor,
	FollowTargetTypeMarket,
}

func (e FollowTargetType) IsValid() bool {
	switch e {
	case FollowTargetTypeVendor, FollowTargetTypeMarket:
		return true
	}
	return false
}

func (e FollowTargetType) String() string {
	return string(e)
}

func (e *FollowTargetType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FollowTargetType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FollowTargetType", str)
	}
	return nil
}

func (e FollowTargetType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FollowTargetType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FollowTargetType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type InvitationStatus string

const (
	InvitationStatusPending  InvitationStatus = "PENDING"
	InvitationStatusAccepted InvitationStatus = "ACCEPTED"
	InvitationStatusDeclined InvitationStatus = "DECLINED"
)

var AllInvitationStatus = []InvitationStatus{
	InvitationStatusPending,
	InvitationStatusAccepted,
	InvitationStatusDeclined,
}

func (e InvitationStatus) IsValid() bool {
	switch e {
	case InvitationStatusPending, InvitationStatusAccepted, InvitationStatusDeclined:
		return true
	}
	return false
}

func (e InvitationStatus) String() string {
	return string(e)
}

func (e *InvitationStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InvitationStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InvitationStatus", str)
	}
	return nil
}

func (e InvitationStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InvitationStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InvitationStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MarketStatus string

const (
	MarketStatusActive     MarketStatus = "ACTIVE"
	MarketStatusCancelled  MarketStatus = "CANCELLED"
	MarketStatusEndedEarly MarketStatus = "ENDED_EARLY"
)

var AllMarketStatus = []MarketStatus{
	MarketStatusActive,
	MarketStatusCancelled,
	MarketStatusEndedEarly,
}

func (e MarketStatus) IsValid() bool {
	switch e {
	case MarketStatusActive, MarketStatusCancelled, MarketStatusEndedEarly:
		return true
	}
	return false
}

func (e MarketStatus) String() string {
	return string(e)
}

func (e *MarketStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MarketStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MarketStatus", str)
	}
	return nil
}

func (e MarketStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MarketStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MarketStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Platform string

const (
	PlatformIos     Platform = "IOS"
	PlatformAndroid Platform = "ANDROID"
	PlatformWeb     Platform = "WEB"
)

var AllPlatform = []Platform{
	PlatformIos,
	PlatformAndroid,
	PlatformWeb,
}

func (e Platform) IsValid() bool {
	switch e {
	case PlatformIos, PlatformAndroid, PlatformWeb:
		return true
	}
	return false
}

func (e Platform) String() string {
	return string(e)
}

func (e *Platform) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Platform(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Platform", str)
	}
	return nil
}

func (e Platform) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Platform) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Platform) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Authentication types and mutations.
// Handles Firebase Auth login/signup flows and role management.
type Role string

const (
	RoleCustomer Role = "CUSTOMER"
	RoleVendor   Role = "VENDOR"
	RoleManager  Role = "MANAGER"
)

var AllRole = []Role{
	RoleCustomer,
	RoleVendor,
	RoleManager,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleCustomer, RoleVendor, RoleManager:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ScheduleType string

const (
	ScheduleTypeRecurring ScheduleType = "RECURRING"
	ScheduleTypeOneTime   ScheduleType = "ONE_TIME"
)

var AllScheduleType = []ScheduleType{
	ScheduleTypeRecurring,
	ScheduleTypeOneTime,
}

func (e ScheduleType) IsValid() bool {
	switch e {
	case ScheduleTypeRecurring, ScheduleTypeOneTime:
		return true
	}
	return false
}

func (e ScheduleType) String() string {
	return string(e)
}

func (e *ScheduleType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ScheduleType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ScheduleType", str)
	}
	return nil
}

func (e ScheduleType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ScheduleType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ScheduleType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type VendorMarketJoinStatus string

const (
	VendorMarketJoinStatusPending  VendorMarketJoinStatus = "PENDING"
	VendorMarketJoinStatusApproved VendorMarketJoinStatus = "APPROVED"
	VendorMarketJoinStatusRejected VendorMarketJoinStatus = "REJECTED"
	VendorMarketJoinStatusMixed    VendorMarketJoinStatus = "MIXED"
)

var AllVendorMarketJoinStatus = []VendorMarketJoinStatus{
	VendorMarketJoinStatusPending,
	VendorMarketJoinStatusApproved,
	VendorMarketJoinStatusRejected,
	VendorMarketJoinStatusMixed,
}

func (e VendorMarketJoinStatus) IsValid() bool {
	switch e {
	case VendorMarketJoinStatusPending, VendorMarketJoinStatusApproved, VendorMarketJoinStatusRejected, VendorMarketJoinStatusMixed:
		return true
	}
	return false
}

func (e VendorMarketJoinStatus) String() string {
	return string(e)
}

func (e *VendorMarketJoinStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = VendorMarketJoinStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid VendorMarketJoinStatus", str)
	}
	return nil
}

func (e VendorMarketJoinStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *VendorMarketJoinStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e VendorMarketJoinStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type VendorRosterStatus string

const (
	VendorRosterStatusPending      VendorRosterStatus = "PENDING"
	VendorRosterStatusApproved     VendorRosterStatus = "APPROVED"
	VendorRosterStatusRejected     VendorRosterStatus = "REJECTED"
	VendorRosterStatusInvited      VendorRosterStatus = "INVITED"
	VendorRosterStatusCommitted    VendorRosterStatus = "COMMITTED"
	VendorRosterStatusNotAttending VendorRosterStatus = "NOT_ATTENDING"
)

var AllVendorRosterStatus = []VendorRosterStatus{
	VendorRosterStatusPending,
	VendorRosterStatusApproved,
	VendorRosterStatusRejected,
	VendorRosterStatusInvited,
	VendorRosterStatusCommitted,
	VendorRosterStatusNotAttending,
}

func (e VendorRosterStatus) IsValid() bool {
	switch e {
	case VendorRosterStatusPending, VendorRosterStatusApproved, VendorRosterStatusRejected, VendorRosterStatusInvited, VendorRosterStatusCommitted, VendorRosterStatusNotAttending:
		return true
	}
	return false
}

func (e VendorRosterStatus) String() string {
	return string(e)
}

func (e *VendorRosterStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = VendorRosterStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid VendorRosterStatus", str)
	}
	return nil
}

func (e VendorRosterStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *VendorRosterStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e VendorRosterStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
