// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AddScheduleInput struct {
	MarketID  string `json:"marketID"`
	DayOfWeek int32  `json:"dayOfWeek"`
	StartTime string `json:"startTime"`
	EndTime   string `json:"endTime"`
}

type AuditLogConnection struct {
	Entries    []*AuditLogEntry `json:"entries"`
	TotalCount int32            `json:"totalCount"`
	HasMore    bool             `json:"hasMore"`
}

// Audit log query types (read-only, no mutations).
// Audit writes are handled exclusively by PostgreSQL triggers.
type AuditLogEntry struct {
	ID         string  `json:"id"`
	ActorID    string  `json:"actorID"`
	ActorRole  string  `json:"actorRole"`
	ActionType string  `json:"actionType"`
	TargetType string  `json:"targetType"`
	TargetID   string  `json:"targetID"`
	MarketID   *string `json:"marketID,omitempty"`
	Timestamp  string  `json:"timestamp"`
	Payload    *string `json:"payload,omitempty"`
}

type AuditLogFilter struct {
	ActorID    *string `json:"actorID,omitempty"`
	ActionType *string `json:"actionType,omitempty"`
	TargetType *string `json:"targetType,omitempty"`
	TargetID   *string `json:"targetID,omitempty"`
	MarketID   *string `json:"marketID,omitempty"`
	StartDate  *string `json:"startDate,omitempty"`
	EndDate    *string `json:"endDate,omitempty"`
}

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type CheckIn struct {
	ID           string        `json:"id"`
	VendorID     string        `json:"vendorID"`
	MarketID     string        `json:"marketID"`
	Status       CheckInStatus `json:"status"`
	CheckedInAt  string        `json:"checkedInAt"`
	CheckedOutAt *string       `json:"checkedOutAt,omitempty"`
}

type CheckInInput struct {
	MarketID string `json:"marketID"`
}

type CreateMarketInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Address     string  `json:"address"`
	Latitude    float64 `json:"latitude"`
	Longitude   float64 `json:"longitude"`
	ImageURL    *string `json:"imageURL,omitempty"`
}

type CreateProductInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Category    *string `json:"category,omitempty"`
	ImageURL    *string `json:"imageURL,omitempty"`
}

type CreateUserInput struct {
	Role Role   `json:"role"`
	Name string `json:"name"`
}

type CreateUserPayload struct {
	User *User `json:"user"`
}

type CreateVendorProfileInput struct {
	BusinessName string  `json:"businessName"`
	Description  *string `json:"description,omitempty"`
	ImageURL     *string `json:"imageURL,omitempty"`
}

// Customer profile, follows, and discovery queries.
type CustomerProfile struct {
	ID              string    `json:"id"`
	UserID          string    `json:"userID"`
	DisplayName     string    `json:"displayName"`
	FollowedVendors []*Vendor `json:"followedVendors"`
	FollowedMarkets []*Market `json:"followedMarkets"`
	CreatedAt       string    `json:"createdAt"`
	UpdatedAt       string    `json:"updatedAt"`
}

type DeviceToken struct {
	ID        string   `json:"id"`
	UserID    string   `json:"userID"`
	Token     string   `json:"token"`
	Platform  Platform `json:"platform"`
	CreatedAt string   `json:"createdAt"`
}

type ExceptionStatusInput struct {
	CheckInID string `json:"checkInID"`
	Reason    string `json:"reason"`
}

type Follow struct {
	ID         string           `json:"id"`
	CustomerID string           `json:"customerID"`
	TargetType FollowTargetType `json:"targetType"`
	TargetID   string           `json:"targetID"`
	CreatedAt  string           `json:"createdAt"`
}

type FollowingFeedItem struct {
	ID        string  `json:"id"`
	Type      string  `json:"type"`
	Vendor    *Vendor `json:"vendor,omitempty"`
	Market    *Market `json:"market,omitempty"`
	Timestamp string  `json:"timestamp"`
	Message   string  `json:"message"`
}

type LoginInput struct {
	FirebaseToken string `json:"firebaseToken"`
}

// Market profile, schedule, and roster types.
// Managed by Market Managers.
type Market struct {
	ID          string               `json:"id"`
	Name        string               `json:"name"`
	Description *string              `json:"description,omitempty"`
	Address     string               `json:"address"`
	Latitude    float64              `json:"latitude"`
	Longitude   float64              `json:"longitude"`
	ImageURL    *string              `json:"imageURL,omitempty"`
	Managers    []*User              `json:"managers"`
	Schedule    []*MarketSchedule    `json:"schedule"`
	Vendors     []*VendorRosterEntry `json:"vendors"`
	CreatedAt   string               `json:"createdAt"`
	UpdatedAt   string               `json:"updatedAt"`
}

type MarketSchedule struct {
	ID        string `json:"id"`
	MarketID  string `json:"marketID"`
	DayOfWeek int32  `json:"dayOfWeek"`
	StartTime string `json:"startTime"`
	EndTime   string `json:"endTime"`
}

// Root Mutation type - extended by each domain schema.
// No audit mutations exist; audit writes are DB trigger-only.
type Mutation struct {
}

// Notification preferences and device token management.
type NotificationPreferences struct {
	ID                  string `json:"id"`
	UserID              string `json:"userID"`
	PushEnabled         bool   `json:"pushEnabled"`
	VendorCheckInAlerts bool   `json:"vendorCheckInAlerts"`
	MarketUpdateAlerts  bool   `json:"marketUpdateAlerts"`
	ExceptionAlerts     bool   `json:"exceptionAlerts"`
	CreatedAt           string `json:"createdAt"`
	UpdatedAt           string `json:"updatedAt"`
}

type Product struct {
	ID          string  `json:"id"`
	VendorID    string  `json:"vendorID"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Category    *string `json:"category,omitempty"`
	ImageURL    *string `json:"imageURL,omitempty"`
	IsAvailable bool    `json:"isAvailable"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
}

// Root Query type - extended by each domain schema.
type Query struct {
}

type RegisterDeviceTokenInput struct {
	Token    string   `json:"token"`
	Platform Platform `json:"platform"`
}

type SignUpInput struct {
	FirebaseToken string `json:"firebaseToken"`
	DisplayName   string `json:"displayName"`
	Role          Role   `json:"role"`
}

type UpdateMarketInput struct {
	Name        *string  `json:"name,omitempty"`
	Description *string  `json:"description,omitempty"`
	Address     *string  `json:"address,omitempty"`
	Latitude    *float64 `json:"latitude,omitempty"`
	Longitude   *float64 `json:"longitude,omitempty"`
	ImageURL    *string  `json:"imageURL,omitempty"`
}

type UpdateNotificationPreferencesInput struct {
	PushEnabled         *bool `json:"pushEnabled,omitempty"`
	VendorCheckInAlerts *bool `json:"vendorCheckInAlerts,omitempty"`
	MarketUpdateAlerts  *bool `json:"marketUpdateAlerts,omitempty"`
	ExceptionAlerts     *bool `json:"exceptionAlerts,omitempty"`
}

type UpdateProductInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Category    *string `json:"category,omitempty"`
	ImageURL    *string `json:"imageURL,omitempty"`
	IsAvailable *bool   `json:"isAvailable,omitempty"`
}

type UpdateVendorProfileInput struct {
	BusinessName *string `json:"businessName,omitempty"`
	Description  *string `json:"description,omitempty"`
	ImageURL     *string `json:"imageURL,omitempty"`
}

type User struct {
	ID          string `json:"id"`
	FirebaseUID string `json:"firebaseUID"`
	Email       string `json:"email"`
	DisplayName string `json:"displayName"`
	Role        Role   `json:"role"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

// Vendor profile, product catalog, and check-in types.
type Vendor struct {
	ID           string     `json:"id"`
	UserID       string     `json:"userID"`
	BusinessName string     `json:"businessName"`
	Description  *string    `json:"description,omitempty"`
	ImageURL     *string    `json:"imageURL,omitempty"`
	Products     []*Product `json:"products"`
	CheckIns     []*CheckIn `json:"checkIns"`
	CreatedAt    string     `json:"createdAt"`
	UpdatedAt    string     `json:"updatedAt"`
}

type VendorRosterEntry struct {
	ID       string       `json:"id"`
	MarketID string       `json:"marketID"`
	VendorID string       `json:"vendorID"`
	Vendor   *Vendor      `json:"vendor"`
	Status   RosterStatus `json:"status"`
	Date     string       `json:"date"`
}

type CheckInStatus string

const (
	CheckInStatusCheckedIn  CheckInStatus = "CHECKED_IN"
	CheckInStatusCheckedOut CheckInStatus = "CHECKED_OUT"
	CheckInStatusException  CheckInStatus = "EXCEPTION"
)

var AllCheckInStatus = []CheckInStatus{
	CheckInStatusCheckedIn,
	CheckInStatusCheckedOut,
	CheckInStatusException,
}

func (e CheckInStatus) IsValid() bool {
	switch e {
	case CheckInStatusCheckedIn, CheckInStatusCheckedOut, CheckInStatusException:
		return true
	}
	return false
}

func (e CheckInStatus) String() string {
	return string(e)
}

func (e *CheckInStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CheckInStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CheckInStatus", str)
	}
	return nil
}

func (e CheckInStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CheckInStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CheckInStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FollowTargetType string

const (
	FollowTargetTypeVendor FollowTargetType = "VENDOR"
	FollowTargetTypeMarket FollowTargetType = "MARKET"
)

var AllFollowTargetType = []FollowTargetType{
	FollowTargetTypeVendor,
	FollowTargetTypeMarket,
}

func (e FollowTargetType) IsValid() bool {
	switch e {
	case FollowTargetTypeVendor, FollowTargetTypeMarket:
		return true
	}
	return false
}

func (e FollowTargetType) String() string {
	return string(e)
}

func (e *FollowTargetType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FollowTargetType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FollowTargetType", str)
	}
	return nil
}

func (e FollowTargetType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FollowTargetType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FollowTargetType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Platform string

const (
	PlatformIos     Platform = "IOS"
	PlatformAndroid Platform = "ANDROID"
)

var AllPlatform = []Platform{
	PlatformIos,
	PlatformAndroid,
}

func (e Platform) IsValid() bool {
	switch e {
	case PlatformIos, PlatformAndroid:
		return true
	}
	return false
}

func (e Platform) String() string {
	return string(e)
}

func (e *Platform) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Platform(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Platform", str)
	}
	return nil
}

func (e Platform) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Platform) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Platform) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Authentication types and mutations.
// Handles Firebase Auth login/signup flows and role management.
type Role string

const (
	RoleCustomer Role = "CUSTOMER"
	RoleVendor   Role = "VENDOR"
	RoleManager  Role = "MANAGER"
)

var AllRole = []Role{
	RoleCustomer,
	RoleVendor,
	RoleManager,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleCustomer, RoleVendor, RoleManager:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RosterStatus string

const (
	RosterStatusPending  RosterStatus = "PENDING"
	RosterStatusApproved RosterStatus = "APPROVED"
	RosterStatusRejected RosterStatus = "REJECTED"
)

var AllRosterStatus = []RosterStatus{
	RosterStatusPending,
	RosterStatusApproved,
	RosterStatusRejected,
}

func (e RosterStatus) IsValid() bool {
	switch e {
	case RosterStatusPending, RosterStatusApproved, RosterStatusRejected:
		return true
	}
	return false
}

func (e RosterStatus) String() string {
	return string(e)
}

func (e *RosterStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RosterStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RosterStatus", str)
	}
	return nil
}

func (e RosterStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RosterStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RosterStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
