/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,jsx,ts,tsx}', './components/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        primary: {
          0: 'rgb(var(--color-primary-0))',
          50: 'rgb(var(--color-primary-50))',
          100: 'rgb(var(--color-primary-100))',
          200: 'rgb(var(--color-primary-200))',
          300: 'rgb(var(--color-primary-300))',
          400: 'rgb(var(--color-primary-400))',
          500: 'rgb(var(--color-primary-500))',
          600: 'rgb(var(--color-primary-600))',
          700: 'rgb(var(--color-primary-700))',
          800: 'rgb(var(--color-primary-800))',
          900: 'rgb(var(--color-primary-900))',
          950: 'rgb(var(--color-primary-950))',
        },
        background: {
          0: 'rgb(var(--color-background-0))',
          50: 'rgb(var(--color-background-50))',
          100: 'rgb(var(--color-background-100))',
          200: 'rgb(var(--color-background-200))',
          300: 'rgb(var(--color-background-300))',
          400: 'rgb(var(--color-background-400))',
          500: 'rgb(var(--color-background-500))',
          DEFAULT: 'rgb(var(--color-background-0))',
        },
        typography: {
          0: 'rgb(var(--color-typography-0))',
          50: 'rgb(var(--color-typography-50))',
          100: 'rgb(var(--color-typography-100))',
          200: 'rgb(var(--color-typography-200))',
          300: 'rgb(var(--color-typography-300))',
          400: 'rgb(var(--color-typography-400))',
          500: 'rgb(var(--color-typography-500))',
          600: 'rgb(var(--color-typography-600))',
          700: 'rgb(var(--color-typography-700))',
          800: 'rgb(var(--color-typography-800))',
          900: 'rgb(var(--color-typography-900))',
          950: 'rgb(var(--color-typography-950))',
        },
        success: { 500: 'rgb(var(--color-success-500))' },
        error: { 500: 'rgb(var(--color-error-500))' },
        warning: { 500: 'rgb(var(--color-warning-500))' },
        info: { 500: 'rgb(var(--color-info-500))' },
      },
    },
  },
  plugins: [],
};
