# Don't modify trigger event, `uses` line, `secrets: inherit`, or job-level `permissions` block!
# Source of truth: petry-projects/.github/standards/workflows/dependabot-automerge.yml
name: Dependabot auto-merge
on:
  pull_request_target:
    branches:
      - main
permissions: {}
jobs:
  dependabot-automerge:
    permissions:
      contents: read
      pull-requests: read
    uses: petry-projects/.github/.github/workflows/dependabot-automerge-reusable.yml@376a4fcb1117444595e3e702fa450873d0e54310 # v2
    secrets: inherit
